apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

patches:
- path: manager_config_patch.yaml

images:
- name: controller
  newName: registry.test.pensando.io:5000/gpu-operator
  newTag: dev

configurations:
- kustomizeconfig.yaml
