apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../rbac-base
  - role.yaml
  - kmm_module_loader_role_binding.yaml
  - kmm_module_loader_service_account.yaml
  - kmm_module_loader_cluster_role.yaml
  - kmm_device_plugin_role_binding.yaml
  - kmm_device_plugin_service_account.yaml
  - kmm_device_plugin_cluster_role.yaml
  - node_labeller_service_account.yaml
  - node_labeller_cluster_role.yaml
  - node_labeller_role_binding.yaml
  - metrics_exporter_service_account.yaml
  - metrics_exporter_cluster_role.yaml
  - metrics_exporter_role_binding.yaml
  - metrics_exporter_rbac_proxy_service_account.yaml
  - metrics_exporter_rbac_proxy_cluster_role.yaml
  - metrics_exporter_rbac_proxy_role_binding.yaml
  - test_runner_service_account.yaml
  - test_runner_role.yaml
  - test_runner_role_binding.yaml
  - utils_container_service_account.yaml
  - utils_container_role.yaml
  - utils_container_role_binding.yaml